"""Transform legacy structured resume dict to JSON Resume schema.

JSON Resume is the industry-standard schema for resume data:
    https://jsonresume.org/schema/

Phase 5 §8.36: We use JSON Resume v1.0.0 with two non-standard extensions
under ``basics`` for resume-AI-specific preferences (these fields are
never auto-generated by AI — see PHASE5_PLAN.md §2.2 field property
matrix; they are user-input only):

    - basics.desiredSalary  (string, optional) — e.g. "12-15K", "面议"
    - basics.desiredLocation (string, optional) — e.g. "北京/远程"

The ``meta.schema_version`` field marks our extension layer for forward
compatibility.
"""

from __future__ import annotations

import re
from typing import Any

SCHEMA_VERSION = "json-resume-1.0.0+resumeai"

_PERIOD_SPLIT_RE = re.compile(r"\s*[-–—~至/]\s*")
_DATE_PARTS_RE = re.compile(r"(?P<y>(?:19|20)\d{2})\s*[年.\-/]?\s*(?P<m>0?\d{1,2})?")
_NOW_RE = re.compile(r"至今|现在|今|now|present", re.I)


def _parse_single_date(s: str) -> str | None:
    """Parse a single date token like '2023年1月' / '2023.01' / '2023' to ISO format.

    Returns ``"YYYY-MM"`` if month found, ``"YYYY"`` if only year, ``None`` if
    unparseable.
    """
    if not s or _NOW_RE.search(s):
        return None
    m = _DATE_PARTS_RE.search(s)
    if not m:
        return None
    year = m.group("y")
    month = m.group("m")
    if month:
        return f"{year}-{int(month):02d}"
    return year


def parse_period(period: str) -> tuple[str | None, str | None]:
    """Parse Chinese resume period like '2023年1月-2024年6月' into (start, end).

    End is ``None`` when text matches '至今/现在/now'. Either side can be
    ``None`` if unparseable.
    """
    if not period:
        return None, None
    parts = _PERIOD_SPLIT_RE.split(period.strip(), maxsplit=1)
    if len(parts) == 1:
        # Single date — treat as start-only
        return _parse_single_date(parts[0]), None
    start = _parse_single_date(parts[0])
    end_text = parts[1].strip() if len(parts) > 1 else ""
    end = None if _NOW_RE.search(end_text) else _parse_single_date(end_text)
    return start, end


def _split_keywords(s: str) -> list[str]:
    """Split a tech-stack-like string into keyword list."""
    if not s:
        return []
    # Try common separators in order
    for sep in [",", "，", "/", "、", "|", " "]:
        if sep in s:
            return [k.strip() for k in s.split(sep) if k.strip() and len(k.strip()) < 30][:20]
    return [s.strip()] if len(s.strip()) < 30 else []


def legacy_to_json_resume(legacy: dict[str, Any]) -> dict[str, Any]:
    """Transform legacy structured dict to JSON Resume schema.

    Legacy schema:
        {basic_info: {name, phone, email, url}, education: [...],
         work_experience: [...], projects: [...], skills: [str], ...}
    """
    if not legacy:
        return _empty_json_resume()

    legacy_basic = legacy.get("basic_info") or {}
    legacy_edu = legacy.get("education") or []
    legacy_work = legacy.get("work_experience") or []
    legacy_projects = legacy.get("projects") or []
    legacy_skills = legacy.get("skills") or []

    return {
        "meta": {"schema_version": SCHEMA_VERSION, "canonical": "https://jsonresume.org/schema/"},
        "basics": {
            "name": legacy_basic.get("name", "") or "",
            "email": legacy_basic.get("email", "") or "",
            "phone": legacy_basic.get("phone", "") or "",
            "url": legacy_basic.get("url", "") or "",
            "summary": "",
            "location": {"city": "", "region": "", "countryCode": ""},
            "profiles": [],
            # Extensions (resume-AI-specific, user-input only — never AI-filled)
            "desiredSalary": None,
            "desiredLocation": None,
        },
        "work": [_to_work(e) for e in legacy_work],
        "education": [_to_education(e) for e in legacy_edu],
        "projects": [_to_project(p) for p in legacy_projects],
        "skills": [{"name": s, "level": "", "keywords": []} for s in legacy_skills if s],
        "languages": [],
        "certificates": [],
        "awards": [],
        "publications": [],
        "interests": [],
        "references": [],
        "volunteer": [],
    }


def _to_work(legacy: dict[str, Any]) -> dict[str, Any]:
    start, end = parse_period(legacy.get("period", ""))
    return {
        "name": legacy.get("company", "") or "",
        "position": legacy.get("position", "") or "",
        "startDate": start or "",
        "endDate": end or "",
        "url": "",
        "summary": legacy.get("description", "") or "",
        "highlights": [],
    }


def _to_education(legacy: dict[str, Any]) -> dict[str, Any]:
    start, end = parse_period(legacy.get("period", ""))
    return {
        "institution": legacy.get("school", "") or "",
        "studyType": legacy.get("degree", "") or "",
        "area": legacy.get("major", "") or "",
        "startDate": start or "",
        "endDate": end or "",
        "url": "",
        "score": "",
        "summary": "",
        "courses": [],
    }


def _to_project(legacy: dict[str, Any]) -> dict[str, Any]:
    start, end = parse_period(legacy.get("period", ""))
    keywords = _split_keywords(legacy.get("tech_stack", ""))
    return {
        "name": legacy.get("name", "") or "",
        "description": legacy.get("description", "") or "",
        "highlights": [],
        "keywords": keywords,
        "startDate": start or "",
        "endDate": end or "",
        "url": "",
        "roles": [],
        "entity": "",
        "type": "",
    }


def _empty_json_resume() -> dict[str, Any]:
    return {
        "meta": {"schema_version": SCHEMA_VERSION, "canonical": "https://jsonresume.org/schema/"},
        "basics": {
            "name": "", "email": "", "phone": "", "url": "", "summary": "",
            "location": {"city": "", "region": "", "countryCode": ""},
            "profiles": [],
            "desiredSalary": None, "desiredLocation": None,
        },
        "work": [], "education": [], "projects": [], "skills": [],
        "languages": [], "certificates": [], "awards": [],
        "publications": [], "interests": [], "references": [], "volunteer": [],
    }


# Public alias for new blank resumes (Phase 5a A2 — used by upload.create_blank_resume)
empty_json_resume = _empty_json_resume
