"""PDF renderer using Playwright headless Chromium.

Phase 5c — Converts resume HTML (generated by frontend themes) into A4 PDF.
The HTML is expected to be self-contained (all CSS inline, no external URLs).

Deployment notes:
- Linux containers need `fonts-noto-cjk` for Chinese glyph rendering.
- Playwright browsers are auto-installed via `playwright install chromium`.
"""

from playwright.sync_api import sync_playwright


def html_to_pdf(html: str, scale: float = 1.0) -> bytes:
    """Render HTML string to PDF bytes (A4, print-background enabled).

    ``scale`` is passed directly to Playwright's ``page.pdf(scale=...)``.
    This is the reliable way to shrink content to fit one page — CSS ``zoom``
    only affects visual rendering and does NOT change print layout boxes.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        # `wait_until="load"` is sufficient for fully-inline HTML (no external assets).
        page.set_content(html, wait_until="load")
        pdf = page.pdf(
            format="A4",
            print_background=True,
            margin={"top": "0", "right": "0", "bottom": "0", "left": "0"},
            scale=scale,
        )
        browser.close()
        return pdf
