"""fix_system_config_unique_constraint

Revision ID: 21fcf4ca0c48
Revises: 7fa4cbca56e0
Create Date: 2026-05-26 13:32:14.735400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fcf4ca0c48'
down_revision: Union[str, Sequence[str], None] = '7fa4cbca56e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_system_config_user_key', ['user_id', 'key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_constraint('uix_system_config_user_key', type_='unique')

    # ### end Alembic commands ###
