"""add_user_auth_and_user_id_to_all_models

Revision ID: 7fa4cbca56e0
Revises: e45bee40c24c
Create Date: 2026-05-26 13:28:31.519281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa4cbca56e0'
down_revision: Union[str, Sequence[str], None] = 'e45bee40c24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_analyses_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_batches_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_batches_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_jobs_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_resumes_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_system_config_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_system_config_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_constraint('fk_system_config_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_system_config_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resumes_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_batches_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_batches_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_analyses_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
