"""add-paragraph-suggestions-to-analysis

Revision ID: b2dd22984799
Revises: 0e528a336a6c
Create Date: 2026-05-09 17:54:05.446179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dd22984799'
down_revision: Union[str, Sequence[str], None] = '0e528a336a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paragraph_suggestions_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('paragraph_suggestions_json')

    # ### end Alembic commands ###
